# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Baltic Earth Winter School
author: Florian Börgel
logo: figures/logo_baltic_earth.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

launch_buttons:
  notebook_interface: "jupyterlab"

# Information about where the book exists on the web
repository:
  url: https://github.com/florianboergel/bwes  # Online location of your book
  path_to_book: .
  branch: main  # Which branch of the repository should be used when creating links (optional)

